<?php

namespace AppBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProduitsByCategorieWithLeftJoin(\AppBundle\Entity\Categorie $cat) {
        
        $qb = $this->createQueryBuilder('p');
        $qb->leftJoin('p.image', 'i')
                ->addSelect('i')
                ->leftJoin('p.categories', 'c')
                ->addSelect('c')
                ->where('p.categories = ?1')
                ->setParameter(1, $cat)
                ->orderBy('p.createdAt', 'DESC');
        
        $query = $qb->getQuery();
        
        return $query->getArrayResult();
        
    }
    
    public function getProduitByIdWithLeftJoin($id) {
        
        $qb = $this->createQueryBuilder('p');
        $qb->leftJoin('p.image', 'i')
                ->addSelect('i')
                ->leftJoin('p.notes', 'n')
                ->addSelect('n')
                ->leftJoin('p.categories', 'c')
                ->addSelect('c')
                ->where('p.id = ?1')
                ->setParameter(1, $id);
        
        $query = $qb->getQuery();
        
        return  $query->getOneOrNullResult();
    }
    
    public function getTroisDernierProduits() {
        
        $qb = $this->createQueryBuilder('p');
        $qb->orderBy('p.createdAt', 'DESC')
                ->setFirstResult(0)
                ->setMaxResults(3);
        
        $query = $qb->getQuery();
        
        return $query->getArrayResult();
    }
}
